### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/wt23-naturdoc#9]
- In-depth explanation of the project including deep dives into the different tracks in the group, describing the process and insights from the development
- Min 750 words
- Should contain illustrative material (images, diagrams, screenshots, etc)
- The blog post should be written as a markdown file and should be committed to GitHub with all the required materials in the GitHub repository.

Final delivery 09/04

**Comment by hotmail030** [comment]
(INFO)
We will need a blog-post from the team, describing your process, your major achievements, design challenges and delivery. [Here is a good example from the past](https://github.com/TechLabs-Berlin/st22-peedom/blob/main/Blog%20Post.md). Please add a  Markdown file with this report and add it to your github repo. You should call this report.md or blog.md so that it is easy for us to identify where this file is.
    In addition, we need a short project description of not more than 130 words to add to your certificate. Please add this to the README file itself at the very top under the name of your repo. If possible please label this section "Summary". In case you want to add a detailed description, feel free to do so but please place the short description at the very top. Failure to comply with this is usually what leads to delays in generating certificates for the whole team, so please do pay attention to this. [A decent example is here](https://github.com/TechLabs-Berlin/wt21-happy-cook).
